name = "Quantiles"
uuid = "991e8b65-5dbe-4c91-aaeb-76935b394def"
authors = ["Fabian Greimel"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
